// Local summaries: no skill descriptions, paths or credentials go to a
// translation service. Always retain the author's full original description.
const chinese: Record<string, string> = {
  'openai-templates': '使用 OpenAI 提供的参考模板创建文档、演示稿和电子表格。',
  imagegen: '按文字或参考图片生成、编辑图片，支持插画、照片、图标和透明背景素材。',
  'openai-docs': '查询 OpenAI 和 Codex 官方资料，协助配置、使用与排查问题。',
  'plugin-creator': '创建 Codex 插件目录、清单和相关技能配置。',
  'skill-creator': '编写或改进自定义技能及其配套文件。',
  'skill-installer': '从推荐目录或 GitHub 仓库安装技能。',
  'review-agent': '审查代码变更，查找缺陷与回归风险。',
  'computer-use': '通过界面操作电脑应用，完成点击、输入和验证。',
  'unified-computer-use': '通过浏览器界面读取页面并完成网页操作。',
  browser: '打开和操作网页，读取页面内容。',
  chrome: '操作 Chrome 浏览器中的页面与标签。',
  'codex-app-tools': '管理 Codex 中的任务、项目、附件和应用设置。',
  documents: '创建、编辑和检查 Word 文档，验证排版和渲染效果。',
  pdf: '读取、生成和编辑 PDF，并检查页面布局。',
  presentations: '创建、编辑和检查 PowerPoint 演示文稿。',
  spreadsheets: '创建、编辑和分析电子表格，处理公式、图表和格式。',
  'excel-live-control': '通过已连接的 Excel 插件操作当前打开的工作簿。',
  'template-creator': '将参考文档、表格或演示稿整理成可复用的个人模板技能。',
  'plugin-management': '发现、安装和管理插件，检查连接状态与所需权限。',
  visualize: '创建交互式图表、演示和可视化工具，帮助理解与比较方案。',
  notion: '连接 Notion，整理知识、研究资料、会议内容和实施计划。',
  'notion-knowledge-capture': '将讨论与决策整理为 Notion 知识库、操作说明和常见问题。',
  'notion-meeting-intelligence': '结合 Notion 背景资料准备会议议程、预读材料和讨论要点。',
  'notion-research-documentation': '检索 Notion 中的资料，整理有来源引用的研究报告。',
  'notion-spec-to-implementation': '把 Notion 产品需求转化为实施计划、任务和进度记录。',
  vercel: '使用 Vercel 相关技能与连接工具，开发、部署和维护网页应用。',
  github: '连接 GitHub，处理仓库、代码、议题和拉取请求。',
  gmail: '连接 Gmail，查阅和处理邮件。',
  sites: '构建、预览和发布网站。',
  'sites-building': '构建完整的网站、仪表板、门户或交互工具。',
  'sites-hosting': '使用 Sites 发布网站，并管理托管部署。',
  'sites-preview-troubleshooting': '排查并恢复 Sites 托管预览环境。',
  'agent-browser': '自动操作浏览器，导航、填写表单、截图并验证网页。',
  'agent-browser-verify': '验证开发服务器页面、关键界面和浏览器控制台错误。',
  'ai-elements': '使用 AI Elements 组件构建聊天、消息、工具调用和推理界面。',
  'ai-gateway': '配置 AI 模型路由、备用供应商和费用跟踪。',
  'ai-generation-persistence': '为 AI 生成内容设计标识、存储、访问地址和成本记录。',
  'ai-sdk': '使用 AI SDK 开发聊天、流式生成、工具调用、嵌入和智能体。',
  auth: '为网页应用集成身份认证和登录流程。',
  bootstrap: '按依赖顺序初始化项目、关联服务并配置开发环境。',
  'cdn-caching': '排查 CDN 缓存命中、过期内容、重新验证与缓存费用。',
  'chat-sdk': '使用 Chat SDK 开发跨平台聊天机器人。',
  cms: '集成内容管理系统，设计内容模型、预览和更新流程。',
  'cron-jobs': '配置定时任务与周期执行规则。',
  'deployments-cicd': '配置部署、持续集成、回滚和发布流程。',
  email: '集成邮件服务，设计和发送事务邮件模板。',
  'env-vars': '管理环境变量、环境文件及不同部署环境的配置。',
  eve: '使用 Eve 构建持久化智能体和可恢复的任务流程。',
  geist: '配置 Geist 字体、排版和相关界面样式。',
  geistdocs: '使用 Geistdocs 构建文档站点及搜索、多语言和部署功能。',
  'investigation-mode': '结合运行日志、流程状态和浏览器验证定位故障。',
  'json-render': '处理 AI 聊天消息、工具结果、流式状态和结构化内容的渲染。',
  'knowledge-update': '补充 Vercel 平台的新能力和更新后的使用方式。',
  marketplace: '通过 Vercel Marketplace 发现、安装和管理第三方集成。',
  micro: '使用 micro 构建轻量异步 HTTP 服务。',
  microfrontends: '设计和部署微前端、多区域路由及独立发布的前端应用。',
  ncc: '使用 ncc 将 Node.js 项目及其依赖打包为独立文件。',
  'next-cache-components': '配置 Next.js 缓存组件、部分预渲染和缓存失效策略。',
  'next-forge': '使用 next-forge 搭建和维护生产级 SaaS 项目。',
  'next-upgrade': '依据官方迁移指南升级 Next.js。',
  nextjs: '开发和排查 Next.js 路由、服务器组件、数据加载及部署问题。',
  observability: '配置应用日志、监控、追踪、性能和访问分析。',
  payments: '集成 Stripe 支付、结账、订阅和回调处理。',
  'react-best-practices': '审查 React 组件结构、Hooks、可访问性、性能和类型设计。',
  'routing-middleware': '使用路由中间件处理请求拦截、重写、重定向与个性化。',
  'runtime-cache': '配置运行时缓存，处理缓存标签和失效。',
  satori: '使用 Satori 将 HTML/CSS 转换为 SVG 或分享卡片图片。',
  shadcn: '安装、组合和定制 shadcn/ui 组件及主题。',
  'sign-in-with-vercel': '为应用集成 Vercel OAuth 登录。',
  swr: '使用 SWR 处理数据获取、缓存、刷新、分页与乐观更新。',
  turbopack: '配置 Turbopack，优化开发构建和热更新。',
  turborepo: '配置单仓库任务、缓存、依赖与持续集成。',
  'v0-dev': '使用 v0 生成界面和代码，并集成到开发与部署流程。',
  'vercel-agent': '使用 Vercel Agent 进行代码审查、问题调查和应用集成。',
  'vercel-api': '通过 Vercel API 管理项目、部署、域名、环境变量和日志。',
  'vercel-cli': '使用 Vercel CLI 配置、部署和排查应用。',
  'vercel-connect': '为应用接入第三方服务的 OAuth 授权。',
  'vercel-firewall': '配置 Vercel 防火墙、访问规则、限流和攻击防护。',
  'vercel-flags': '配置功能开关、分阶段发布和实验。',
  'vercel-functions': '配置、优化和排查 Vercel 无服务器函数。',
  'vercel-queues': '构建异步任务、事件分发和延迟消息队列。',
  'vercel-sandbox': '在隔离沙箱中运行代码和临时构建任务。',
  'vercel-services': '在一个 Vercel 项目中配置和部署多个服务。',
  'vercel-storage': '选择和集成对象存储、配置存储及数据库。',
  verification: '从浏览器到 API 和数据层验证完整功能流程。',
  workflow: '构建可暂停、重试和恢复的持久化工作流。',
}

export function describeExtension(name: string, original: string): string {
  if (/[\u3400-\u9fff]/u.test(original)) return original
  const key = name.split(':').pop()!.toLowerCase()
  const templateNames: Record<string, string> = {
    'analytics-dashboard': '分析仪表板', 'business-review': '业务复盘', 'design-report': '设计报告',
    'experiment-analysis': '实验分析', 'financial-budget': '财务预算', 'investment-committee-memo': '投资委员会备忘录',
    'legal-memorandum': '法律备忘录', 'market-trends-report': '市场趋势报告', 'minimal-letterhead': '简洁信笺',
    'operating-calendar': '运营日历', 'operating-review': '运营复盘', 'project-kickoff': '项目启动文稿',
    'project-tracker': '项目跟踪表', 'sales-pipeline': '销售进展表', 'simple-dark-mode': '简洁深色文稿',
    'simple-light-mode': '简洁浅色文稿', 'strategy-memorandum': '战略备忘录',
  }
  const template = templateNames[key.replace(/^artifact-template-/, '')]
  if (key.startsWith('artifact-template-') && template) return `使用参考模板创建${template}，并遵循模板的结构、样式和排版要求。`
  return chinese[key] || original || '作者未提供说明。'
}
